theme: osuny
_merge: deep
params:
  debug:
    productionUrl: https://www.degrowthjournal.org
  breadcrumb:
    position: hero-end
  summary:
    position: hero
  papers:
    sidebar:
      direction: end
